config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  comfy_route :cms_admin, path: '/admin'
  comfy_route :blog_admin, path: 'admin'

  resource :my_profile, only: [:show, :edit, :update], controller: 'my_profile'
  resources :events
  root to: 'blog_posts#index'

  # Make sure this routeset is defined last
  comfy_route :cms, path: '/', sitemap: false
  comfy_route :blog, path: 'blog'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: User
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, foreign_key: :creator_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.nickname = auth.info.name
      user.image_url = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < Comfy::Blog::PostsController
  expose(:near_events)

  private

  def near_events
    Event.where('start_at > ?', Time.now).order('start_at').last(3)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  expose(:event, attributes: :event_params)
  expose(:events)

  def create
    if event.save
      redirect_to event, notice: t('events.create.success')
    else
      render action: 'new'
    end
  end

  def update
    if event.save
      redirect_to event, notice: t('events.update.success')
    else
      render action: 'edit'
    end
  end

  def destroy
    event.destroy
    redirect_to events_url, notice: t('events.destroy.success')
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_at, :end_at)
  end
end

app/controllers/my_profile_controller.rb
class MyProfileController < ApplicationController
  def update
    if current_user.update_attributes(my_profile_params)
      redirect_to my_profile_path, notice: t('common.update_success')
    else
      render :edit
    end
  end

  private

  def my_profile_params
    params.require(:user).permit(:nickname)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comfy/blog/comments/_form.html.slim
= comfy_form_for @comment, :as => :comment, :url => comfy_blog_comments_path(@cms_site.path, @blog.path, @post.slug) do |form|

  / don't need this when installed into your app
  = form.hidden_field :authenticity_token, :value => form_authenticity_token

  = form.text_field :author
  = form.text_field :email
  = form.text_area :content

  = form.submit 'Submit'

app/views/comfy/blog/posts/index.html.slim
.col-md-9
  - near_events.each do |event|
    .col-md-4
      h1= event.name
      p= event.description
      p= event.start_at
      p= event.end_at
      .row
        = link_to 'Dolacz', event, class: 'btn btn-success'
        = link_to 'Wiecej informacji', event, class: 'btn btn-primary'

.col-md-3.text-center
    = link_to 'Stwórz własny event', new_event_path, class: 'btn btn-primary btn-lg'

.col-md-9

  - @posts.each do |post|

    h1= link_to post.title, comfy_blog_post_path(@cms_site.path, @blog.path, post.slug)
    .author
      = post.author
    .date
      = post.published_at.to_s(:db)
    .content
      = post.content.html_safe

.col-md-3.text-center
  h1 Coming Events
  = link_to 'Wyświetl wszystkie eventy', events_path, class: 'btn btn-primary btn-lg'

= paginate @posts

app/views/comfy/blog/posts/show.html.slim
h1= @post.title

.author
  = @post.author
.date
  = @post.published_at.to_s(:db)
.content
  = @post.content.html_safe

.comments
  - @post.comments.published.each do |comment|
    .comment
      .author= comment.author
      .content= comment.content

  = render :partial => 'comfy/blog/comments/form'

app/views/events/_form.html.slim
.row
  .col-lg-6
    = simple_form_for(event) do |f|
      = f.error_notification
      .form-inputs
        = f.input :name
        = f.input :description
        = f.input :start_at
        = f.input :end_at
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.button :submit, class: 'btn btn-primary'
  .col-lg-6
    #map.map
coffee:
  new EventMap('map')

app/views/events/edit.html.slim
page-header
  h3= t('events.update.header')

= render 'form'

app/views/events/index.html.slim
.page-header
  h1= t('.header')

.page-actions.text-right
  = link_to 'Stwórz event', new_event_path, class: 'btn btn-success'
  .br

table.table
  thead
    tr
      th= t('events.index.name')
      th= t('event.index.description')
      th= t('event.index.start_at')
      th= t('event.index.end_at')
      th

  - events.each do |event|
    tr
      td= event.name
      td= event.description
      td= event.start_at
      td= event.end_at
      td
        = link_to 'Show', event, class: 'btn btn-default'
        = link_to 'Edit', edit_event_path(event), class: 'btn btn-primary'
        = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/events/new.html.slim
page-header
  h3= t('events.create.header')

= render 'form'

app/views/events/show.html.slim
br
.panel.panel-default
  .panel-body
    .page-actions.text-right
      = link_to 'Edit', edit_event_path(event), class: 'btn btn-primary'
    .row
      .col-md-2
        = image_tag 'http://www.positioniseverything.net/articles/images/ds2-main.png'
      .col-md-10
        h1= event.name
        p= event.description
        p= event.start_at
        p= event.end_at
    .row
      .col-md-12
        = image_tag 'http://placehold.it/1500x600'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li= link_to t('navigation.about_authors'), '/about-authors'
- if current_user
  li= link_to t('navigation.my_profile'), my_profile_path
  |
  li= link_to t('navigation.sign_out'), destroy_user_session_path
- else
  li= link_to t('navigation.sign_in'), user_omniauth_authorize_path(:facebook)

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Clean Forrest'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Clean Forrest'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/my_profile/edit.html.slim
h1= t('my_profile.edit.header')

= simple_form_for current_user, url: my_profile_path, method: :put do |f|
  = f.input :nickname
  = f.submit

app/views/my_profile/show.html.slim
h1= t('my_profile.show.header')
= link_to t('common.edit'), edit_my_profile_path

= image_tag current_user.image_url

b= t('profile.email')
= current_user.email
br
b= t('profile.nickname')
= current_user.nickname

app/views/visitors/index.html.slim
h3 Welcome